Repository System-Garcia/node-pets, pull requests merged in 2024-03, with the labels that each got.

#70 Implement User-Specific Pet Listing Endpoint
  api/src/domain/datasources/pet.datasource.ts
  api/src/domain/index.ts
  api/src/domain/repositories/pet.repository.ts
  api/src/domain/use-cases/pet/get-user-pets.ts
  api/src/infrastructure/datasources/pets/postgres-pet.datasource.ts
  api/src/infrastructure/repositories/pet.repository.ts
  api/src/presentation/pets/controller.ts
  api/src/presentation/pets/routes.ts
Labels: backend, feature

#72 feat - Implement Pet Update Endpoint
  api/src/domain/dtos/pets/update-pet.dto.ts
  api/src/domain/index.ts
  api/src/domain/repositories/pet.repository.ts
  api/src/domain/use-cases/pet/update-pet.ts
  api/src/infrastructure/datasources/pets/postgres-pet.datasource.ts
  api/src/infrastructure/repositories/pet.repository.ts
  api/src/presentation/pets/controller.ts
  api/src/presentation/pets/routes.ts
Labels: backend, feature

#75 Create location and reward
  api/prisma/migrations/20240326004539_add_created_at_and_updated_at/migration.sql
  api/prisma/migrations/20240326013134_add_longitude_latitude_description/migration.sql
  api/prisma/schema.prisma
  api/prisma/seed/data.ts
  api/src/domain/datasources/location.datasource.ts
  api/src/domain/datasources/reward.datasource.ts
  api/src/domain/dtos/locations/create-location.dto.ts
  api/src/domain/dtos/locations/update-location.dto.ts
  api/src/domain/dtos/rewards/create-reward.dto.ts
  api/src/domain/dtos/rewards/update-reward.dto.ts
  api/src/domain/entities/comment.entity.ts
  api/src/domain/entities/location.entity.ts
  api/src/domain/entities/reward.entity.ts
  api/src/domain/index.ts
  api/src/domain/interfaces/paginated-reward-res.interface.ts
  api/src/domain/repositories/location.repository.ts
  api/src/domain/repositories/reward.repository.ts
  api/src/domain/services/reward-service.ts
  api/src/domain/use-cases/location/create-location.ts
  api/src/domain/use-cases/reward/create-reward.ts
  api/src/infrastructure/datasources/locations/postgres-location.datasource.ts
  api/src/infrastructure/datasources/rewards/postgres-reward.datasource.ts
  api/src/infrastructure/repositories/location.repository.ts
  api/src/infrastructure/repositories/reward.repository.ts
  api/src/presentation/middlewares/reward.middleware.ts
  api/src/presentation/rewards/controller.ts
  api/src/presentation/rewards/routes.ts
  api/src/presentation/routes.ts
  api/src/presentation/services/reward.service.ts
Labels: backend, refactor, feature

#73 feat: setlement of environtment variables
  client/.env.template
  client/.gitignore
  client/src/components/pages/CreateAccount.jsx
  client/src/components/pages/EmailValidation.jsx
  client/src/components/pages/ForgotPassword.jsx
  client/src/components/pages/ResetPassword.jsx
  client/src/context/AuthContext.jsx
Labels: quality, performance
