Repository System-Garcia/node-pets, pull requests merged in 2024-04, with the labels that each got.

#77 Delete cachestorybookdefaultdev server of dev
  .cache/storybook/default/dev-server/a5a8bf6e622aef57065c6498611f40c911543d7d-3920d97c51b8ad2521918fb1205babd22b0ed3d7
  .cache/storybook/default/dev-server/a5a8bf6e622aef57065c6498611f40c911543d7d-43fdebe5fc35e4e9fabee9a83c7faea931b05ea0
  .cache/storybook/default/dev-server/a5a8bf6e622aef57065c6498611f40c911543d7d-f086b87885981c04ce7a583ff90a49313de83de7
Labels: bug

#78 feat - Implement Reward Deletion
  api/package-lock.json
  api/src/domain/datasources/reward.datasource.ts
  api/src/domain/index.ts
  api/src/domain/repositories/reward.repository.ts
  api/src/domain/services/reward-service.ts
  api/src/domain/use-cases/reward/delete-reward.ts
  api/src/infrastructure/datasources/rewards/postgres-reward.datasource.ts
  api/src/infrastructure/repositories/reward.repository.ts
  api/src/presentation/middlewares/reward.middleware.ts
  api/src/presentation/rewards/controller.ts
  api/src/presentation/rewards/routes.ts
  api/src/presentation/services/reward.service.ts
Labels: backend, feature

#79 34 reward update including location details
  api/src/domain/index.ts
  api/src/domain/interfaces/updateRewardAndLocationData.interface.ts
  api/src/domain/services/reward-service.ts
  api/src/domain/use-cases/reward/update-reward.ts
  api/src/infrastructure/datasources/rewards/postgres-reward.datasource.ts
  api/src/presentation/middlewares/reward.middleware.ts
  api/src/presentation/rewards/controller.ts
  api/src/presentation/rewards/routes.ts
  api/src/presentation/services/reward.service.ts
Labels: backend, feature

#81 Create a Public API Endpoint for Fetching Reward Details
  api/src/domain/datasources/reward.datasource.ts
  api/src/domain/repositories/reward.repository.ts
  api/src/domain/services/reward-service.ts
  api/src/infrastructure/datasources/rewards/postgres-reward.datasource.ts
  api/src/infrastructure/repositories/reward.repository.ts
  api/src/presentation/rewards/controller.ts
  api/src/presentation/rewards/routes.ts
  api/src/presentation/services/reward.service.ts
Labels: backend, feature

#83 Species Management Interface Implementation
  api/README.md
  client/public/assets/icons/navbar/ic_specie.svg
  client/public/img/homepage/availables/savePet.png
  client/public/img/homepage/availables/socialize.png
  client/public/img/homing.png
  client/src/components/atoms/HamsterWheel.jsx
  client/src/components/molecules/Card.jsx
  client/src/components/pages/HomePageLog.jsx
  client/src/components/pages/LoginPage.jsx
  client/src/context/AuthContext.jsx
  client/src/hooks/useLoginFields .js
  client/src/layouts/dashboard/config-navigation.jsx
  client/src/sections/products/view/products-view.jsx
  client/src/styles/atoms/hamsterWheel.module.css
  client/src/styles/pages/homepageL.module.css
  client/src/styles/pages/loginPage.module.css
Labels: frontend, ui/ux

#85 Feature: Real-Time Species Listing on Management Page
  client/src/_mock/products.js
  client/src/components/pages/MainMenu.jsx
  client/src/helpers/axiosHelper.js
  client/src/sections/products/view/products-view.jsx
Labels: frontend, ui/ux

#87 Refactor auth context and axios helper
  client/src/_mock/products.js
  client/src/auth/context/AuthContext.jsx
  client/src/auth/context/AuthProvider.jsx
  client/src/auth/context/authReducer.js
  client/src/auth/context/index.js
  client/src/auth/types/types.js
  client/src/components/pages/CreateAccount.jsx
  client/src/components/pages/LoginPage.jsx
  client/src/context/AuthContext.jsx
  client/src/helpers/axiosHelper.js
  client/src/helpers/httpHelper.js
  client/src/helpers/index.js
  client/src/main.jsx
  client/src/sections/products/view/products-view.jsx
Labels: frontend, quality, refactor

#89 Refactor Styles for LoginPage to Improve Responsiveness on Mobile and Desktop
  client/package.json
  client/src/components/pages/LoginPage.jsx
  client/src/styles/base/index.css
  client/src/styles/pages/loginPage.module.css
  client/yarn.lock
Labels: frontend, refactor, ui/ux

#90 Implement Species Listing on Management Page (#28)
  api/prisma/seed/data.ts
  client/src/components/pages/DashboardPage.jsx
  client/src/sections/products/product-card.jsx
  client/src/sections/products/view/products-view.jsx
  client/src/stories/Button.jsx
  client/src/stories/Button.stories.js
  client/src/stories/Configure.mdx
  client/src/stories/Header.jsx
  client/src/stories/Header.stories.js
  client/src/stories/Page.jsx
  client/src/stories/Page.stories.js
  client/src/stories/assets/accessibility.png
  client/src/stories/assets/accessibility.svg
  client/src/stories/assets/addon-library.png
  client/src/stories/assets/assets.png
  client/src/stories/assets/avif-test-image.avif
  client/src/stories/assets/context.png
  client/src/stories/assets/discord.svg
  client/src/stories/assets/docs.png
  client/src/stories/assets/figma-plugin.png
  client/src/stories/assets/github.svg
  client/src/stories/assets/share.png
  client/src/stories/assets/styling.png
  client/src/stories/assets/testing.png
  client/src/stories/assets/theming.png
  client/src/stories/assets/tutorials.svg
  client/src/stories/assets/youtube.svg
  client/src/stories/button.css
  client/src/stories/header.css
  client/src/stories/page.css
Labels: enhancement, frontend, feature, ui/ux

#95 Enhancements to Authentication Flow and Route Protection
  api/package-lock.json
  api/package.json
  client/src/App.jsx
  client/src/auth/context/AuthProvider.jsx
  client/src/components/animations/Loaders.jsx
  client/src/components/pages/MainMenu.jsx
  client/src/router/GeneralProtectedRoute.jsx
  client/src/router/ProtectedRoute.jsx
  client/src/styles/atoms/loaders.module.css
  client/src/styles/pages/loginPage.module.css
  client/src/styles/pages/mainMenu.module.css
Labels: frontend, feature, performance, high

#98 feat - Admin login logs
  api/.gitignore
  api/src/presentation/services/auth.service.ts
Labels: backend, feature, security

#99 Display Created Rewards in Main Menu Using Card Format
  client/src/App.jsx
  client/src/components/pages/CreatePet.jsx
  client/src/components/pages/MainMenu.jsx
  client/src/components/pages/MyPetsPage.jsx
  client/src/layouts/dashboard/common/account-popover.jsx
  client/src/layouts/dashboard/nav.jsx
  client/src/styles/pages/mainMenu.module.css
  client/src/styles/pages/myPets.module.css
Labels: frontend, feature, medium
